language: node_js
node_js:
  - '4'
  - '5'
sudo: false
before_install:
  - npm install -g npm@latest
notifications:
  slack:
    secure: 1T2Nq/oEabq7/ABfNAX6WRMUtQehOO9aY7936LSovQ8W7KhFGdmD3WRL9x855qLuIJxPwway90xNs8uhb+JJtvYTJAQ5+j1Tk+N6MO59dpccphUHVOwlegrbjKkoXR0LXUiYLTevPjuYxdupqBjy4g4SLgKy60wQIT2lsSC4Q1MFUdTr7ufZe3dhmgbcHSo896hv2vzewFG1u4gKJYkpJMWX15BoUfTddFI5fIozP0tD0fGkrJVJaDjA88q8Qi4TAVXU9RH1QWxnozIsVhGw7u3sDP5T9UHkjYUmgW/KPpuOf55UqniIhQiVLyr9Fe4ER78uBAC+1slwYQPAdsnSYqxoIT7F1tZXuliis32VW6k7Un3M8UDAQZRxlcqXRUE/pEqp11rC/hic/6pVLg80IJ+HCzhdIPtT4utgXnNr9zUlpIpFkcwL172hktnUT/5IjRSt0p9YF0iGXoDr8bm3Wuq+mx6UqDyMLIMGZCMeqRKG+r6SASyPsRGMNuZ1iEOeApidnRJPR1yEgFoW6nXyleu3Kj2PA2ffVjyP2Cg0uW80AVlLnmC/bWai5QH3ZJR0aYyPV6ypTHtuvZdgRmRehY2HPME4azrX2gney8oODe6Kg90eSeB+igbn3Xid272440peju//Hthj/D1BC7HIM0cMfHnOzWKaudOAMr1ve9c=
